name: resortdemo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Architecture
  flutter_clean_architecture: ^5.0.0

  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.0
  cloud_firestore: ^3.4.0

  #stylish bottom var
  motion_tab_bar_v2: ^0.2.6

  #page transition
  page_transition: ^2.0.9

  #animations
  lottie: ^1.2.1

  # custom pop up package
  rflutter_alert: ^2.0.4

  #permission handler
  permission_handler: ^10.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/home.jpg
    - assets/animations/spa_fitness.gif
    - assets/animations/nutirition.gif
    - assets/animations/health_tracking.gif
    - assets/animations/clinical_treatment.gif
    - assets/animations/intellectual_development.gif
    - assets/animations/social_recognition.gif
    - assets/images/onwater_villa.jpg
    - assets/images/underwater_bed.jpg
    - assets/images/weekend_apartment.jpg
    - assets/images/Longevity_inTime.png
    - assets/images/Longevity_inTimesvg.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
